import { test, expect, type Page } from '@playwright/test';

// ============================================================
// UX FLOW AUDIT — Generated by ux-flow-audit skill
// Date: 2026-02-23
// Run: npx playwright test tests/ux-flow-audit.spec.ts
// Run headed: npx playwright test tests/ux-flow-audit.spec.ts --headed
// ============================================================

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function uniqueEmail() {
  return `audit-test-${Date.now()}@seer-test.invalid`;
}

async function clearAuthState(page: Page) {
  await page.context().clearCookies();
  await page.evaluate(() => localStorage.clear());
}

// Simulate a logged-in returning user by injecting auth state.
// Uses the same token format as the real app (JWT stored as 'auth-token').
async function loginAs(page: Page, opts: { coinsUsed?: number } = {}) {
  // Navigate to /login and register a fresh user for test isolation.
  const email = uniqueEmail();
  const password = 'TestPassword8!';
  const firstName = 'Auditor';

  await page.goto('/login');
  await page.getByRole('button', { name: /Create an account/i }).click();

  await page.getByLabel('First Name').fill(firstName);
  await page.getByLabel('Email').fill(email);
  await page.getByLabel('Password').fill(password);
  await page.getByRole('button', { name: /Create Account/i }).click();

  // In test env (NODE_ENV=test or DISABLE_RATE_LIMIT=true), email is auto-verified
  // and user is logged in immediately — no email verification required.
  // If verification screen appears, the test environment is not configured for auto-verify.
  const isAutoVerified = await page.getByText(/Choose your guide|Preparing your session/i)
    .isVisible({ timeout: 5000 })
    .catch(() => false);

  if (!isAutoVerified) {
    // Skip tests that require a logged-in user in non-test envs
    test.skip();
  }
}

// ---------------------------------------------------------------------------
// Suite 1: New Visitor Journey — Happy Path
// ---------------------------------------------------------------------------

test.describe('New Visitor Journey', () => {
  test.beforeEach(async ({ page }) => {
    await clearAuthState(page);
  });

  test('NV-01: /personas loads without auth and shows guide directory', async ({ page }) => {
    await page.goto('/personas');
    await expect(page.getByRole('heading', { name: 'Choose your guide' })).toBeVisible();
    // Should not redirect to /login
    await expect(page).not.toHaveURL(/\/login/);
  });

  test('NV-02: promo banner "3 FREE minutes" visible to logged-out users', async ({ page }) => {
    await page.goto('/personas');
    await expect(page.getByText('3 FREE minutes')).toBeVisible({ timeout: 5000 });
  });

  test('NV-03: clicking Start Chat in top "Voted Most Accurate" section opens auth modal', async ({ page }) => {
    await page.goto('/personas');
    // Wait for persona cards to load
    await page.waitForSelector('[class*="mp-card"]', { timeout: 10000 });
    // Click the first "Start Chat" button (top section)
    await page.getByRole('button', { name: 'Start Chat' }).first().click();
    // Auth modal should appear
    await expect(page.getByRole('dialog')).toBeVisible({ timeout: 3000 });
  });

  test('NV-04: auth modal shows the persona name in its title', async ({ page }) => {
    await page.goto('/personas');
    await page.waitForSelector('[class*="mp-card"]', { timeout: 10000 });
    // Click first Start Chat
    await page.getByRole('button', { name: 'Start Chat' }).first().click();
    const dialog = page.getByRole('dialog');
    await expect(dialog).toBeVisible();
    // Modal should show a persona name (dialog title has the persona's display name)
    // The modal title is a DialogTitle — verify it has text content
    const title = dialog.getByRole('heading');
    await expect(title).not.toBeEmpty();
  });

  test('NV-05: auth modal shows persona avatar image', async ({ page }) => {
    await page.goto('/personas');
    await page.waitForSelector('[class*="mp-card"]', { timeout: 10000 });
    await page.getByRole('button', { name: 'Start Chat' }).first().click();
    const dialog = page.getByRole('dialog');
    await expect(dialog).toBeVisible();
    // Modal shows an avatar image
    const avatar = dialog.locator('img').first();
    await expect(avatar).toBeVisible();
  });

  test('NV-06: auth modal sign-up form shows "3 FREE minutes" badge', async ({ page }) => {
    await page.goto('/personas');
    await page.waitForSelector('[class*="mp-card"]', { timeout: 10000 });
    await page.getByRole('button', { name: 'Start Chat' }).first().click();
    const dialog = page.getByRole('dialog');
    await expect(dialog).toBeVisible();
    await expect(dialog.getByText('3 FREE minutes')).toBeVisible();
  });

  test('NV-07: submitting registration in auth modal with valid data shows verification screen', async ({ page }) => {
    await page.goto('/personas');
    await page.waitForSelector('[class*="mp-card"]', { timeout: 10000 });
    await page.getByRole('button', { name: 'Start Chat' }).first().click();
    const dialog = page.getByRole('dialog');
    await expect(dialog).toBeVisible();

    // Fill in the form
    const email = uniqueEmail();
    await dialog.locator('input[type="text"]').fill('Auditor');
    await dialog.locator('input[type="email"]').fill(email);
    await dialog.locator('input[type="password"]').fill('SecurePass8!');
    await dialog.getByRole('button', { name: /Create Account/i }).click();

    // In test env → auto-verified → navigates to /reading
    // In production env → shows "Check Your Email" screen
    const autoVerified = await page.waitForURL(/\/reading/, { timeout: 8000 }).then(() => true).catch(() => false);
    if (!autoVerified) {
      await expect(dialog.getByRole('heading', { name: 'Check Your Email' })).toBeVisible({ timeout: 5000 });
    }
  });

  test('NV-08: after login with verified account, /reading loads the chat interface', async ({ page }) => {
    await page.goto('/login');
    // Sign in (assumes a pre-existing test account or test env auto-verify)
    // This test documents the post-login destination
    await expect(page.getByRole('heading', { name: /Welcome Back|Create Account/i })).toBeVisible();
  });
});

// ---------------------------------------------------------------------------
// Suite 2: Returning User Journey — Happy Path
// ---------------------------------------------------------------------------

test.describe('Returning User Journey', () => {
  test('RU-01: authenticated user with spent coins sees no promo banner', async ({ page }) => {
    // This test requires a logged-in user with totalCoinsUsed > 0.
    // In CI, inject a stubbed auth response. Here we verify the DOM condition.
    await page.goto('/personas');
    const banner = page.getByText('3 FREE minutes', { exact: false });

    // If logged in as returning user, banner should NOT be visible
    // We can only fully verify this with real auth — document the expected behaviour
    // The guard in code is: !authLoading && !isReturningUser (PersonasDirectory.tsx:767)
    // Test passes if either: user is not logged in (banner visible) OR user is returning (banner absent)
    const isLoggedIn = await page.getByRole('button', { name: 'Sign In' }).isVisible().catch(() => false);
    if (isLoggedIn) {
      // Guest — banner should be visible
      await expect(banner).toBeVisible({ timeout: 5000 });
    }
    // Returning user state requires proper auth fixture — document as pending
  });

  test('RU-02: authenticated user clicking Start Chat navigates directly to /reading', async ({ page }) => {
    // Requires auth state — run only with storage state fixture
    await page.goto('/personas');
    // If not authenticated, we can verify the auth modal appears (new user path)
    // If authenticated (with storageState), verify direct navigation
    const isGuest = await page.getByText('3 FREE minutes').isVisible({ timeout: 3000 }).catch(() => false);
    if (isGuest) {
      // This is a guest session — skip direct navigation assertion
      test.skip();
      return;
    }
    await page.waitForSelector('[class*="mp-card"]', { timeout: 10000 });
    await page.getByRole('button', { name: 'Start Chat' }).first().click();
    await page.waitForURL(/\/reading|\/chat\//, { timeout: 5000 });
    await expect(page).toHaveURL(/\/reading|\/chat\//);
  });

  test('RU-03: /reading loads and shows persona greeting after guide is selected', async ({ page }) => {
    // Requires auth — annotate
    await page.goto('/reading');
    // If unauthenticated, redirects to /login
    const redirected = await page.waitForURL('/login', { timeout: 3000 }).then(() => true).catch(() => false);
    if (redirected) {
      test.skip(); // Needs auth state fixture
      return;
    }
    // If authenticated, persona greeting should appear
    await page.waitForSelector('[data-testid="chat-greeting"]', { timeout: 15000 });
    const greeting = page.locator('[data-testid="chat-greeting"]');
    await expect(greeting).toBeVisible();
    await expect(greeting).not.toBeEmpty();
  });

  test('RU-04: chat history is visible in the reading ended state', async ({ page }) => {
    // Requires an auth session — annotate expected behavior
    await page.goto('/reading');
    const redirected = await page.waitForURL('/login', { timeout: 3000 }).then(() => true).catch(() => false);
    if (redirected) { test.skip(); return; }

    // Start a session and end it
    await page.waitForSelector('[data-testid="chat-input"]', { timeout: 15000 });
    await page.locator('[data-testid="chat-input"]').fill('Hello');
    await page.locator('[data-testid="send-button"]').click();

    // Wait for a response
    await page.waitForSelector('[data-testid="assistant-message"]', { timeout: 30000 });

    // End reading
    await page.getByRole('button', { name: 'End Reading' }).click();
    await page.getByRole('button', { name: 'End Reading' }).last().click(); // confirm dialog

    // History should still be visible
    await expect(page.getByText('Reading ended')).toBeVisible({ timeout: 5000 });
    await expect(page.getByRole('button', { name: 'Start a New Reading' })).toBeVisible();
  });

  test('RU-05: switching guides during session shows toast notification', async ({ page }) => {
    test.slow(); // involves real AI responses
    await page.goto('/reading');
    const redirected = await page.waitForURL('/login', { timeout: 3000 }).then(() => true).catch(() => false);
    if (redirected) { test.skip(); return; }

    // Start a session
    await page.waitForSelector('[data-testid="chat-input"]', { timeout: 15000 });
    await page.locator('[data-testid="chat-input"]').fill('Hi');
    await page.locator('[data-testid="send-button"]').click();
    await page.waitForSelector('[data-testid="assistant-message"]', { timeout: 30000 });

    // Switch guide via sidebar (first guide button that is not the current guide)
    const sidebarButton = page.locator('[data-testid="guide-sidebar"] button').nth(1);
    if (await sidebarButton.isVisible()) {
      await sidebarButton.click();
      // Toast notification should appear
      await expect(page.getByText(/Session with .+ ended/i)).toBeVisible({ timeout: 5000 });
    }
  });
});

// ---------------------------------------------------------------------------
// Suite 3: Friction Point Tests
// ---------------------------------------------------------------------------

test.describe('Friction Points', () => {
  test.beforeEach(async ({ page }) => {
    await clearAuthState(page);
  });

  // FRICTION-1: Password minimum length mismatch
  test('FRICTION-1-TEST: password shorter than 8 chars shows specific error message, not generic', async ({ page }) => {
    await page.goto('/personas');
    await page.waitForSelector('[class*="mp-card"]', { timeout: 10000 });
    await page.getByRole('button', { name: 'Start Chat' }).first().click();
    const dialog = page.getByRole('dialog');
    await expect(dialog).toBeVisible();

    // Fill form with a 6-character password (below server minimum of 8)
    await dialog.locator('input[type="text"]').fill('Tester');
    await dialog.locator('input[type="email"]').fill(uniqueEmail());
    await dialog.locator('input[type="password"]').fill('abc123');
    await dialog.getByRole('button', { name: /Create Account/i }).click();

    // Error should clearly state the password requirement
    // Currently shows server message; after fix should say "at least 8 characters"
    await expect(dialog.getByText(/8 characters|password.*8|minimum/i)).toBeVisible({ timeout: 5000 });

    // Should NOT show generic "Something went wrong"
    await expect(dialog.getByText(/something went wrong/i)).not.toBeVisible();
  });

  // FRICTION-2: Start Chat crash in Love & Recommended sections
  test('FRICTION-2-TEST: Start Chat in "Best In Love Readings" section does not crash', async ({ page }) => {
    await page.goto('/personas');
    await page.waitForSelector('[class*="mp-card"]', { timeout: 10000 });

    // Find the "Best In Love Readings" section
    const loveSection = page.getByText('Best In Love Readings').locator('..');
    if (!(await loveSection.isVisible())) {
      test.skip(); // Section only appears if love-category guides exist
      return;
    }

    // Collect any JS errors
    const errors: string[] = [];
    page.on('pageerror', err => errors.push(err.message));

    // Click Start Chat in the Love section
    const startChatInLove = loveSection.locator('..').getByRole('button', { name: 'Start Chat' }).first();
    if (await startChatInLove.isVisible()) {
      await startChatInLove.click();
      // Should open auth modal OR navigate — not throw an error
      await page.waitForTimeout(1000);
      const runtimeCrashed = errors.some(e => e.includes('is not a function') || e.includes('undefined'));
      expect(runtimeCrashed).toBe(false);
      // Should show auth modal or have navigated
      const modalOrNav = await page.getByRole('dialog').isVisible().catch(() => false)
        || page.url().includes('/reading');
      expect(modalOrNav).toBe(true);
    }
  });

  // FRICTION-2 (Recommended section)
  test('FRICTION-2-TEST-B: Start Chat in "Recommended For You" section does not crash', async ({ page }) => {
    await page.goto('/personas');
    await page.waitForSelector('[class*="mp-card"]', { timeout: 10000 });

    const recommendedSection = page.getByText('Recommended For You').locator('..');
    if (!(await recommendedSection.isVisible())) { test.skip(); return; }

    const errors: string[] = [];
    page.on('pageerror', err => errors.push(err.message));

    const startChatBtn = recommendedSection.locator('..').getByRole('button', { name: 'Start Chat' }).first();
    if (await startChatBtn.isVisible()) {
      await startChatBtn.click();
      await page.waitForTimeout(1000);
      const runtimeCrashed = errors.some(e => e.includes('is not a function') || e.includes('undefined'));
      expect(runtimeCrashed).toBe(false);
    }
  });

  // FRICTION-3: Persona context lost after email verification
  test('FRICTION-3-TEST: persona slug is preserved when navigating to reading after login', async ({ page }) => {
    // Simulate user who registered after clicking on a specific guide
    // Then navigated to /login?verified=success and signed in
    // Expected: /reading?persona=<slug> — NOT just /reading

    // Navigate to /reading?persona=evelyn-cross as a returning user would
    await page.goto('/reading?persona=evelyn-cross');

    // Unauthenticated → redirects to login (note: currently loses persona param — FRICTION-5 too)
    await page.waitForURL(/\/login/, { timeout: 5000 }).catch(() => {});
    const currentUrl = page.url();

    // After fix: URL should be /login?returnTo=%2Freading%3Fpersona%3Develyn-cross
    // Currently: URL is just /login (no returnTo) — this assertion documents the desired state
    const hasReturnTo = currentUrl.includes('returnTo') && currentUrl.includes('persona');
    // This will FAIL until FRICTION-3 + FRICTION-5 are fixed — documents the bug
    expect(hasReturnTo).toBe(true);
  });

  // FRICTION-4: Auth modal inputs missing name attributes
  test('FRICTION-4-TEST: auth modal form inputs have name attributes for autofill', async ({ page }) => {
    await page.goto('/personas');
    await page.waitForSelector('[class*="mp-card"]', { timeout: 10000 });
    await page.getByRole('button', { name: 'Start Chat' }).first().click();
    const dialog = page.getByRole('dialog');
    await expect(dialog).toBeVisible();

    // Check for name attributes on form inputs
    const firstNameInput = dialog.locator('input[type="text"]');
    const emailInput = dialog.locator('input[type="email"]');
    const passwordInput = dialog.locator('input[type="password"]');

    // These assertions document the DESIRED state (post-fix)
    await expect(firstNameInput).toHaveAttribute('name', 'firstName');
    await expect(emailInput).toHaveAttribute('name', 'email');
    await expect(passwordInput).toHaveAttribute('name', 'password');
  });

  // FRICTION-5: No returnTo in layout redirect to /login
  test('FRICTION-5-TEST: accessing /reading?persona=slug while unauthenticated preserves persona in redirect', async ({ page }) => {
    await clearAuthState(page);
    await page.goto('/reading?persona=evelyn-cross');

    // Should redirect to login WITH returnTo param
    await page.waitForURL(/\/login/, { timeout: 5000 });
    const loginUrl = page.url();

    // After fix: should include returnTo containing the persona param
    // Currently: just /login — documents the desired state
    expect(loginUrl).toContain('returnTo');
    expect(loginUrl).toContain('persona');
  });

  // FRICTION-6: Credit depletion checked only every 60s
  test('FRICTION-6-TEST: out-of-credits modal appears when coins run out during session', async ({ page }) => {
    test.slow();
    await page.goto('/reading');
    const redirected = await page.waitForURL('/login', { timeout: 3000 }).then(() => true).catch(() => false);
    if (redirected) { test.skip(); return; }

    await page.waitForSelector('[data-testid="chat-input"]', { timeout: 15000 });
    await page.locator('[data-testid="chat-input"]').fill('Test message');
    await page.locator('[data-testid="send-button"]').click();

    // If user has 0 coins after session start, OOC modal should appear
    // This test documents the expected modal appearance — real credit depletion takes time
    // In CI: use a test user with 1 coin to trigger fast depletion
    const oocModal = page.getByText("You've run out of credits");
    // The modal SHOULD appear promptly (within 1 billing interval of zero)
    // Document the expected timing — actual assertion requires zero-balance fixture
  });

  // FRICTION-7: No refill warning for paid users with low balance
  test('FRICTION-7-TEST: refill banner shown to user with low coins, not showing "free trial" copy to paid user', async ({ page }) => {
    await page.goto('/reading');
    const redirected = await page.waitForURL('/login', { timeout: 3000 }).then(() => true).catch(() => false);
    if (redirected) { test.skip(); return; }

    // When the refill banner appears, it should NOT say "free trial" for a paying user
    // This test documents the desired state — requires auth fixture with paid + low balance
    const refillBanner = page.getByText(/free trial is ending/i);
    // After fix: paid users should see "You have less than 2 minutes remaining"
    // and NOT see "free trial is ending"
    // Document: if banner appears for paid user, it should have correct copy
    if (await refillBanner.isVisible({ timeout: 5000 }).catch(() => false)) {
      await expect(page.getByText(/free trial is ending/i)).not.toBeVisible();
    }
  });

  // FRICTION-8: Fake strikethrough price in OutOfCreditsModal
  test('FRICTION-8-TEST: OutOfCreditsModal does not show a fake strikethrough original price', async ({ page }) => {
    // Trigger OOC modal by manipulating state — simplest: navigate to /reading with zero coins
    // In test env: check modal markup directly
    await page.goto('/reading');
    const redirected = await page.waitForURL('/login', { timeout: 3000 }).then(() => true).catch(() => false);
    if (redirected) { test.skip(); return; }

    // If OOC modal appears (low balance), verify no fake strikethrough
    const oocModal = page.locator('[role="dialog"]').filter({ hasText: "You've run out of credits" });
    if (await oocModal.isVisible({ timeout: 3000 }).catch(() => false)) {
      // Strikethrough element should not exist (it's a <span> with line-through class)
      const strikethroughPrice = oocModal.locator('span.line-through');
      await expect(strikethroughPrice).not.toBeVisible();
    }
  });

  // FRICTION-9: Auth modal closes on outside click during verification
  test('FRICTION-9-TEST: auth modal stays open after clicking outside when in verification sent state', async ({ page }) => {
    await page.goto('/personas');
    await page.waitForSelector('[class*="mp-card"]', { timeout: 10000 });
    await page.getByRole('button', { name: 'Start Chat' }).first().click();
    const dialog = page.getByRole('dialog');
    await expect(dialog).toBeVisible();

    // Register (will show verification screen in production)
    await dialog.locator('input[type="text"]').fill('Tester');
    await dialog.locator('input[type="email"]').fill(uniqueEmail());
    await dialog.locator('input[type="password"]').fill('SecurePass8!');
    await dialog.getByRole('button', { name: /Create Account/i }).click();

    // In production: verification screen should appear
    const verifyScreen = dialog.getByRole('heading', { name: 'Check Your Email' });
    const autoVerified = !(await verifyScreen.isVisible({ timeout: 5000 }).catch(() => false));
    if (autoVerified) { test.skip(); return; } // Test env auto-verifies — skip

    // With verification screen shown: click outside the modal
    await page.keyboard.press('Escape');

    // After fix: modal should stay open (preventOutsideClose when in verificationSent state)
    // Currently: modal closes — this assertion documents the desired state
    await expect(dialog).toBeVisible({ timeout: 1000 });
    await expect(verifyScreen).toBeVisible();
  });

  // FRICTION-12: Auth loading race — persona context lost
  test('FRICTION-12-TEST: clicking Start Chat during auth loading does not navigate without auth check', async ({ page }) => {
    // Simulate slow auth by throttling network
    await clearAuthState(page);
    await page.goto('/personas');

    // Intercept the /api/auth/me call to delay it
    await page.route('/api/auth/me', async (route) => {
      await new Promise(resolve => setTimeout(resolve, 2000)); // 2s delay
      await route.continue();
    });

    await page.reload();
    await page.waitForSelector('[class*="mp-card"]', { timeout: 10000 });

    // Click Start Chat while auth is still loading (within 2s window)
    await page.getByRole('button', { name: 'Start Chat' }).first().click();

    // After fix: button should do nothing or show loading while authLoading=true
    // Currently: navigates to /reading speculatively, which may then redirect to /login
    await page.waitForTimeout(500);
    const url = page.url();

    // Should NOT have navigated to /reading yet (auth still loading)
    // After fix: still on /personas, or showing auth modal
    const navigatedPrematurely = url.includes('/reading') || url.includes('/chat/');
    expect(navigatedPrematurely).toBe(false);
  });

  // FRICTION-16: View All buttons have no handler
  test('FRICTION-16-TEST: "View All" section buttons are either functional or absent', async ({ page }) => {
    await page.goto('/personas');
    await page.waitForSelector('[class*="mp-card"]', { timeout: 10000 });

    // Find all "View All" buttons
    const viewAllButtons = page.getByRole('button', { name: /View All/i });
    const count = await viewAllButtons.count();

    if (count === 0) {
      // Buttons have been removed — acceptable resolution
      expect(count).toBe(0);
      return;
    }

    // If buttons exist, each should do something when clicked
    const errors: string[] = [];
    page.on('pageerror', err => errors.push(err.message));

    await viewAllButtons.first().click();
    await page.waitForTimeout(500);

    // After clicking: should have navigated or filtered — page should have changed
    // Currently: nothing happens — this assertion documents the desired state
    // A "View All" click should filter, navigate, or scroll to more results
    const didSomething = errors.length === 0; // at minimum should not crash
    expect(didSomething).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// Suite 4: Credit & Onboarding Edge Cases
// ---------------------------------------------------------------------------

test.describe('Credit & Onboarding Edge Cases', () => {
  test('EC-01: credit balance is visible in nav when logged in', async ({ page }) => {
    await page.goto('/personas');
    const redirected = await page.waitForURL('/login', { timeout: 2000 }).then(() => true).catch(() => false);
    if (!redirected) {
      // On /personas with auth, CreditBadge should show in nav
      const creditBadge = page.locator('nav').getByText(/coins|min/i);
      // Only visible when authenticated
      if (await page.getByRole('button', { name: 'Sign In' }).isVisible()) {
        // Guest — no credit badge in nav (correct)
        await expect(creditBadge).not.toBeVisible();
      }
    }
  });

  test('EC-02: "Timer starts when you send your first message" is shown below input after greeting', async ({ page }) => {
    await page.goto('/reading');
    const redirected = await page.waitForURL('/login', { timeout: 3000 }).then(() => true).catch(() => false);
    if (redirected) { test.skip(); return; }

    // Wait for the greeting to load and input to appear
    await page.waitForSelector('[data-testid="chat-input"]', { timeout: 20000 });
    // The "Timer starts..." hint should be visible below the input
    await expect(page.getByText(/Timer starts when you send your first message/i)).toBeVisible();
  });

  test('EC-03: out-of-credits modal shows "Get credits" button', async ({ page }) => {
    // In test env with zero coins, OOC modal should appear after first message
    // This test documents the desired UI state
    await page.goto('/reading');
    const redirected = await page.waitForURL('/login', { timeout: 3000 }).then(() => true).catch(() => false);
    if (redirected) { test.skip(); return; }

    // If OOC modal is visible, verify it has the Get Credits CTA
    const modal = page.locator('[role="dialog"]').filter({ hasText: "You've run out of credits" });
    if (await modal.isVisible({ timeout: 2000 }).catch(() => false)) {
      await expect(modal.getByRole('button', { name: /Get credits/i })).toBeVisible();
      await expect(modal.getByText(/I don't want to continue reading/i)).toBeVisible();
    }
  });

  test('EC-04: idle warning banner appears during active session after inactivity', async ({ page }) => {
    test.slow();
    test.setTimeout(200000);
    await page.goto('/reading');
    const redirected = await page.waitForURL('/login', { timeout: 3000 }).then(() => true).catch(() => false);
    if (redirected) { test.skip(); return; }

    await page.waitForSelector('[data-testid="chat-input"]', { timeout: 15000 });
    await page.locator('[data-testid="chat-input"]').fill('Hello');
    await page.locator('[data-testid="send-button"]').click();
    await page.waitForSelector('[data-testid="assistant-message"]', { timeout: 30000 });

    // Wait 2min + a few seconds for idle warning (125s total)
    await page.waitForSelector('text=Are you still there?', { timeout: 135000 });
    await expect(page.getByText(/Are you still there/i)).toBeVisible();
    await expect(page.getByRole('button', { name: /I'm here/i })).toBeVisible();
  });

  test('EC-05: dismissing idle warning with "I\'m here" stops auto-end countdown', async ({ page }) => {
    test.slow();
    test.setTimeout(200000);
    await page.goto('/reading');
    const redirected = await page.waitForURL('/login', { timeout: 3000 }).then(() => true).catch(() => false);
    if (redirected) { test.skip(); return; }

    await page.waitForSelector('[data-testid="chat-input"]', { timeout: 15000 });
    await page.locator('[data-testid="chat-input"]').fill('Start');
    await page.locator('[data-testid="send-button"]').click();
    await page.waitForSelector('[data-testid="assistant-message"]', { timeout: 30000 });

    // Wait for idle warning
    await page.waitForSelector('text=Are you still there?', { timeout: 135000 });
    // Click "I'm here" to dismiss
    await page.getByRole('button', { name: /I'm here/i }).click();
    // Warning should disappear
    await expect(page.getByText(/Are you still there/i)).not.toBeVisible({ timeout: 3000 });
    // Session should still be active
    await expect(page.getByRole('button', { name: /End Reading/i })).toBeVisible();
  });

  test('EC-06: /personas "View Profile" opens detail modal with persona info', async ({ page }) => {
    await clearAuthState(page);
    await page.goto('/personas');
    await page.waitForSelector('[class*="mp-card"]', { timeout: 10000 });
    await page.getByRole('button', { name: 'View Profile' }).first().click();
    const detailModal = page.getByRole('dialog');
    await expect(detailModal).toBeVisible({ timeout: 5000 });
    // Should show persona name, stats, and a "Start Reading" CTA
    await expect(detailModal.getByRole('button', { name: /Start Reading/i })).toBeVisible();
  });

  test('EC-07: post-session "Choose a New Guide" button navigates to /personas', async ({ page }) => {
    test.slow();
    await page.goto('/reading');
    const redirected = await page.waitForURL('/login', { timeout: 3000 }).then(() => true).catch(() => false);
    if (redirected) { test.skip(); return; }

    await page.waitForSelector('[data-testid="chat-input"]', { timeout: 15000 });
    await page.locator('[data-testid="chat-input"]').fill('Hi');
    await page.locator('[data-testid="send-button"]').click();
    await page.waitForSelector('[data-testid="assistant-message"]', { timeout: 30000 });

    // End the reading
    await page.getByRole('button', { name: 'End Reading' }).click();
    await page.getByRole('button', { name: 'End Reading' }).last().click();

    // "Choose a New Guide" should appear
    await expect(page.getByRole('button', { name: /Choose a New Guide/i })).toBeVisible({ timeout: 5000 });
    await page.getByRole('button', { name: /Choose a New Guide/i }).click();
    await expect(page).toHaveURL('/personas');
  });
});
