// GENERATED by scripts/build-read-copy.mjs from fb-read/docs/drafts/ — do not hand-edit.
// Edit the draft and re-run, or the next regeneration silently reverts you.
//
// SHAPE: seven bubbles per read, written to the Natural Tarot-Cut
// (fb-tarot/docs/natural-tarot-cut.md). Bubble 1 is the picture — on Version C it
// is the ONLY written bubble she sees before she types, so it carries the whole
// first impression, and buildReadReflectPrompt passes it to the model verbatim so
// the reply never re-describes what she has just read.

import type { ReadDevice, ReadHook, ReadOption } from "./readDevices";

export const UNWRITTEN = "__UNWRITTEN__";

export const READS: Partial<
  Record<ReadDevice, Partial<Record<ReadHook, Record<ReadOption, string[]>>>>
> = {
  coffee: {
    "hiding-something": {
      a: [
        "A road, yes. Running along under the rim of your cup, up where the grounds came to rest last.",
        "You asked whether something's being kept from you. A road up near the rim is where the picture stops.",
        "You met a real edge. The road is there in your cup, dear, and you didn't put it there.",
        "The grounds don't say what's past it. They stop exactly where you stopped.",
        "So the road runs and then the grounds end, and you've been standing at that end on your own.",
        "You've been told you're making something out of nothing. The cup shows me you noticed something real.",
        "Let me look closer at what the not-knowing has been costing you…",
      ],
      b: [
        "A tree, yes. Halfway up the wall of your cup, where the grounds caught and held.",
        "You asked whether something's being kept from you. A tree halfway up is what's actually standing there.",
        "It isn't nothing. Something is standing in that cup, and you were right to keep looking at it.",
        "The grounds don't say what it is. Nothing tells me what's behind it either.",
        "So there's something there, and you've had to keep pointing at it by yourself.",
        "You've been called the anxious one for noticing. Noticing isn't the same as inventing, dear.",
        "Let me look closer at what it's taken out of you, being the only one who sees it…",
      ],
      c: [
        "A lake, yes. Lying in the bottom of your cup, where the grounds settled first and stayed.",
        "You asked whether something's being kept from you. A lake on the floor is how deep this has gone in you.",
        "Your read on things is sound. What you're built on hasn't gone wrong, whatever you've been told.",
        "The grounds stop at the water. They don't tell me what's under it.",
        "So it's settled deep in you, and you've been carrying the doubt about yourself as well.",
        "You've begun to doubt your own eyes. That's a heavy thing to be carrying, dear.",
        "Let me look closer at what meeting that edge has cost you…",
      ],
    },
    "love-again": {
      a: [
        "A road, yes. Running along under the rim of your cup, up where the grounds came to rest last.",
        "You asked whether you'll love again. A road up near the rim is the weeks just ahead of you.",
        "Love is coming to you. The road's already in the cup, dear — it isn't waiting on you to find it.",
        "No name comes with it. No face either, and nothing in the grounds tells me when.",
        "So there's a road sitting in your cup, and you've felt none of it moving yet.",
        "You've kept getting up for days that all looked the same. Nobody claps for that, dear.",
        "Let me look closer at what's been keeping that road from reaching you…",
      ],
      b: [
        "A tree, yes. Halfway up the wall of your cup, where the grounds caught and held.",
        "You asked whether you'll love again. A tree halfway up is what's still standing in you now.",
        "You came through it whole. Whatever you think it took from you, the cup still shows me a tree.",
        "The grounds don't say who it's for. Nothing tells me what comes of it either.",
        "So something in you held the whole way through, and it never once felt like it was holding.",
        "You've been treating yourself like the thing that got broken. That isn't what I'm looking at.",
        "Let me look closer at why you've had to hold all of that up on your own…",
      ],
      c: [
        "A lake, yes. Lying in the bottom of your cup, where the grounds settled first and stayed.",
        "You asked whether you'll love again. A lake on the floor of the cup is the ground you were built on.",
        "There's nothing wrong down there. What you were built on is deep, dear, and it's still holding.",
        "No name sits in it. The grounds stop at the water and tell me nothing past it.",
        "So the deep part of you is sound, and you've spent a long time doubting that.",
        "You've gone looking for the fault in yourself, and you've always found one.",
        "Let me look closer at what's been keeping anyone from reaching that deep in you…",
      ],
    },
    "still-think": {
      a: [
        "A road, yes. Running along under the rim of your cup, up where the grounds came to rest last.",
        "You asked whether you still cross his mind. A road up near the rim is what's ahead of you.",
        "The road ahead is yours. Not one bit of it waits on anyone else remembering you first.",
        "The grounds don't say who's on it. Nothing tells me when, either.",
        "So there's a road sitting in your cup, and none of it is his to walk.",
        "You didn't ask for him back. You asked to be remembered, and that's a small thing to want.",
        "Let me look closer at what it's cost you, asking for so little…",
      ],
      b: [
        "A tree, yes. Halfway up the wall of your cup, where the grounds caught and held.",
        "You asked whether you still cross his mind. A tree halfway up is what's still standing from it.",
        "It counted. Something from that time is still standing, and the cup shows me it's standing in you.",
        "The grounds don't say who tended it. Nothing tells me what comes of it either.",
        "So it held, and it's gone on holding without anybody else needing to notice.",
        "You've been told you should be past this by now. The cup doesn't show me a finished thing.",
        "Let me look closer at what's still standing in you from all of that…",
      ],
      c: [
        "A lake, yes. Lying in the bottom of your cup, where the grounds settled first and stayed.",
        "You asked whether you still cross his mind. A lake on the floor is what settled deepest in you.",
        "It's real because it settled in you. What happened isn't kept safe in one person's memory alone.",
        "The grounds stop at the water. They don't tell me what anyone else kept.",
        "So it's down there in you, settled, and it's been there whether or not anyone said so.",
        "You've wondered whether you're the only one who still has it. That wondering has been lonely, dear.",
        "Let me look closer at how long you've held that on your own…",
      ],
    },
  },
  dream: {
    "hiding-something": {
      a: [
        "You're running, and you never turn round to see what's behind you. Your legs won't move the way they should.",
        "You asked whether he's hiding something from you. Never turning round is what it's like when the answer sits somewhere you can't get to.",
        "There's a place where what he tells you stops. You keep meeting it, and you didn't put it there.",
        "Knowing that place is there doesn't tell you a thing about what's in it.",
        "You keep going forward as if there's nothing behind you. Your legs are the part that won't play along.",
        "You don't get a minute's rest from this, dear. Not knowing has been taking it out of you the whole time.",
        "Let me look closer at what's kept you from turning round…",
      ],
      b: [
        "You're falling. There's nothing underneath you, and you wake with that jolt just before you land.",
        "You came asking whether he's hiding something from you. Nothing solid under you means you've had nothing you could put your weight on.",
        "The drop didn't start with you. You've been standing on what you were given, and it doesn't take your weight.",
        "You can feel where it stops, and that doesn't tell you what's underneath. You're awake again before you get that far down.",
        "You've gone on standing on it anyway, and there's still nothing under there holding you up.",
        "Wanting something solid under you isn't an accusation. You've been carrying it like one.",
        "Let's see why solid ground stopped feeling like something you're allowed to want…",
      ],
      c: [
        "Your teeth have gone loose. You put your hand up and they come away, one after another, into your palm.",
        "You asked if he's hiding something from you. Teeth in your palm are bits of a whole you can't put back.",
        "Your hand isn't empty, dear. What's in it came away for real, and nobody gets to tell you it isn't there.",
        "A handful of bits still isn't a picture. You can look at every one and still not know what they belong to.",
        "You know exactly what's in your hand, and it still doesn't tell you what's missing. So you keep holding it.",
        "You've been trying to make a whole man out of what fits in one hand. That's what you've been left with.",
        "Now let me look at what's keeping those bits from adding up…",
      ],
    },
    "love-again": {
      a: [
        "You're running, and you never turn round to see what's behind you. Your legs won't move the way they should.",
        "You're asking if you'll love again. Legs that won't carry you mean you've been trying to get away from something and getting nowhere.",
        "You're not being hunted. What's behind you is the part of you that still wants love, and yes, you'll love again.",
        "The dream shows you running. It doesn't show you stopping, or what you'd do if you turned round.",
        "You still want love, and none has come. Every time this dream comes back, you spend it moving further away.",
        "Keeping ahead of what you want takes everything you've got. No wonder your legs give out.",
        "Let me look closer at what set you running in the first place…",
      ],
      b: [
        "You're falling. There's nothing underneath you, and you wake with that jolt just before you land.",
        "You're asking whether you'll love again. Falling with nothing under you is what it feels like to be held by no one.",
        "You've already made that fall once, and you're still here. Your heart still opens, dear, and love is finding its way back.",
        "The dream stops before you land. Nothing in it ever shows you safe on the ground.",
        "You came through that fall, and you still wake up braced. Your body's still getting ready for a landing that never comes.",
        "You're not asking whether you can love again. You're asking whether anyone will be there to catch you this time.",
        "Let me see what keeps you braced when the fall's already behind you…",
      ],
      c: [
        "Your teeth have gone loose. You put your hand up and they come away, one after another, into your palm.",
        "You're asking if love will come again. Teeth coming out like that is the fear of falling apart where people can see it.",
        "Nothing that mattered was taken. What came away was what you showed people — you can still love, and you will.",
        "The dream ends with them in your palm. You don't see yourself afterwards, and nobody else does either.",
        "You can see exactly what came away, down to the last one. The part that's still yours doesn't show up anywhere.",
        "You'd rather not be looked at too closely just now, and you still want to be loved, dear. Those two pull opposite ways.",
        "Now let me look at what you think you lost with them…",
      ],
    },
    "still-think": {
      a: [
        "You're running, and you never turn round to see what's behind you. Your legs won't move the way they should.",
        "You asked whether he still thinks about you. Never turning round means there's something behind you that you'd rather not look at.",
        "What's behind you is yours, and it was real. You carried it out of there yourself, and you've got it still.",
        "The dream keeps you facing forward. You never turn round, so you never get to see what you're carrying.",
        "So you're carrying it and running from it at the same time, and your legs pay for both.",
        "You've never had a proper look at it, dear. You've just kept going with it at your back.",
        "Let me look closer at what's got you asking for so little of what's yours…",
      ],
      b: [
        "You're falling. There's nothing underneath you, and you wake with that jolt just before you land.",
        "You came asking whether he thinks of you now. No ground under you means there's been nothing firm to stand on.",
        "You didn't fall from nothing, dear. What happened had real weight, and none of it gets lighter if he's set it down.",
        "The dream never lets you land. You wake up in that jolt, and the ground never arrives.",
        "The weight is real, and the dream never gives you anywhere to set it down.",
        "Nobody ever finished this off for you. You've been up in the air with it, and you've asked for next to nothing.",
        "Now let me see what took the ground out from under this…",
      ],
      c: [
        "Your teeth have gone loose. You put your hand up and they come away, one after another, into your palm.",
        "You asked if he thinks of you at all. Teeth going loose is the fear of losing the face people knew you by.",
        "Your face is still your own, and what happened isn't kept in his head alone. You were there for every bit of it.",
        "The dream stops with your hand full. You never get to look up and see yourself whole.",
        "You're holding the lot of it in your palm, and you still can't tell what anyone else sees.",
        "One thought is the smallest thing anyone can ask for. That's what you came for, and it tells me what you've gone without.",
        "Let's look at what's got you measuring yourself by what someone else sees…",
      ],
    },
  },
  tea: {
    "hiding-something": {
      a: [
        "A bird, yes. Wings out, halfway up your cup, and over on the handle side.",
        "You asked whether he's hiding something from you. A bird is word, and yours stopped on your side of the cup.",
        "You met an edge. Meeting one is not the same as imagining one, whatever you've been told.",
        "The bird doesn't say what's past it. Nothing in the leaves names what sits on the other side.",
        "So the word came as far as your side and no further, and you've been filling in the rest yourself.",
        "You noticed something and then had to argue yourself out of it, dear. That's the tiring part.",
        "Let me look closer at what's been stopping the word halfway…",
      ],
      b: [
        "A tree, yes. Halfway up the cup, with its roots running toward the middle.",
        "You asked whether he's hiding something from you. A tree shows you its top, and the roots run where you can't see.",
        "There's a part of this you can't see from where you stand. That's the shape of it, and you didn't put it there.",
        "What's under the ground stays under it. The leaves don't tell me one thing about what's down there.",
        "So you can see the whole tree and still not know the half of it.",
        "You've been asked to take the top of it on trust, dear, and something in you won't.",
        "Let me look closer at what's keeping so much of this underground…",
      ],
      c: [
        "An anchor, yes. Halfway up the cup, on the far side from the handle.",
        "You asked whether he's hiding something from you. An anchor holds, and yours sits over on the far side, out of reach.",
        "There's a place where what you're told stops. You keep arriving at it, and it's real.",
        "The anchor sits on the far side. Nothing in the leaves tells me what it's holding down.",
        "So something's fixed over there, and you've never once been able to get to it.",
        "You've had to keep steady on your own side of this, dear, without a thing to stand on.",
        "Let me look closer at what's kept that anchor out of your reach…",
      ],
    },
    "love-again": {
      a: [
        "A bird, yes. Wings out, halfway up your cup, and over on the handle side.",
        "You asked whether you'll love again. A bird in the leaves is word coming, and yours has landed on your own side.",
        "Love is finding its way back to you. That isn't a maybe, dear — the bird is already in the cup.",
        "No name comes with it. No face either, and nothing in the leaves says when.",
        "So the word is sitting in your cup already, and you haven't felt a thing yet.",
        "You've been waiting on something you had no proof was coming. That's a long thing to do on your own.",
        "Let me look closer at what's been keeping that word from reaching you…",
      ],
      b: [
        "A tree, yes. Halfway up the cup, with its roots running toward the middle.",
        "You asked whether you'll love again. A tree grew from something, and yours has roots that go all the way down.",
        "Your heart came through it whole. What was in you before all this is in you now.",
        "The leaves don't say who it's for. Nothing tells me what comes of it either.",
        "So the roots held the whole way through, and it never once felt like they had.",
        "You've been treating yourself like something that got broken, dear. The cup doesn't show me a broken thing.",
        "Let me look closer at what's been keeping all that growth underground…",
      ],
      c: [
        "An anchor, yes. Halfway up the cup, on the far side from the handle.",
        "You asked whether you'll love again. An anchor is a thing that holds, and yours sits over on the far side.",
        "Steady love is coming to you. It isn't something you have to go out and arrange.",
        "No name, no face. The leaves stop at the anchor and tell me nothing past it.",
        "So there's something steady in your cup, and not one bit of it is in your hands.",
        "You've been doing all the holding on your own, dear. Nobody has taken any of that weight off you.",
        "Let me look closer at why the steady thing keeps stopping short of you…",
      ],
    },
    "still-think": {
      a: [
        "A bird, yes. Wings out, halfway up your cup, and over on the handle side.",
        "You asked whether he still thinks about you. A bird is word, and yours came down on your own side.",
        "What happened was real, and it isn't kept in one head. You were there for it too.",
        "The bird carries no name. Nothing in the leaves tells me what anybody else holds or drops.",
        "So the word landed on your side, and you've spent the whole time waiting on his.",
        "You've scaled it right down, dear. Not his love, not his return — just whether you cross his mind.",
        "Let me look closer at what taught you to ask for so little…",
      ],
      b: [
        "A tree, yes. Halfway up the cup, with its roots running toward the middle.",
        "You asked whether he still thinks about you. A tree is what grew, and yours is rooted deep in the cup.",
        "It grew, and that's in the ground now. Nobody can go back and pull it up.",
        "The tree says nothing about him. Whether it's tended or left alone isn't written in these leaves.",
        "So the roots are yours and they're still holding, and you've been asking someone else to confirm them.",
        "You've been treating your own memory like it needs a second signature, dear.",
        "Let me look closer at when you started needing that from somebody else…",
      ],
      c: [
        "An anchor, yes. Halfway up the cup, on the far side from the handle.",
        "You asked whether he still thinks about you. An anchor is what holds, and yours sits away on the far side.",
        "Something got anchored and it held. It doesn't come loose because one person walked off.",
        "The anchor sits away from your hand. What anybody else carries stays over there, out of these leaves.",
        "So the thing is still moored, and you've been standing here asking whether it counts.",
        "You've been waiting on somebody else's word about a thing you were there for, dear.",
        "Let me look closer at what's kept you standing on this side of it…",
      ],
    },
  },
};

// A read is servable only when it is complete and past the review gate. The
// bridge and the chat route both check this, so a URL handed out early cannot
// serve half-written copy.
export function isReadWritten(
  device: ReadDevice,
  hook: ReadHook,
  option: ReadOption,
): boolean {
  const bubbles = READS[device]?.[hook]?.[option];
  return Array.isArray(bubbles) && bubbles.length === 7 && !bubbles.includes(UNWRITTEN);
}
