#!/usr/bin/env npx tsx
// shadow-drafts-to-registry — fold the APPROVED shadow drafts into the registry's four slots.
//
//   npx tsx scripts/shadow-drafts-to-registry.mts        # → client/src/content/tarotReadsShadow.ts
//
// 🔴 IT COPIES. IT DOES NOT WRITE COPY. Every bubble is moved character-for-character out of
// fb-tarot/docs/drafts/shadow/*.json, which is the approved text. The script folds and nothing
// else, and it verifies its own output by unfolding it again and comparing (see the tail).
//
// THE FOLD, as scripts/lander-registry.mts defines it:
//
//   natural   [picture]        [bridge] [cuts 3-6 joined by \n] [loop]   → slot 0 is ONE line
//   shadow    [claim \n proof] [her]    [but \n so]             [loop]   → slot 0 is TWO lines
//
// Six beats, four slots, six bubbles on her screen — `intoBubbles` in tarotReads.ts splits on
// '\n' at render time. Slot [1] is still the bridge where her ad question comes back and slot
// [3] is still the open loop, so every guard written against the four slots keeps its meaning.
//
// WHY A SEPARATE ROSTER AND NOT AN EDIT TO `DECKS`. This is the 70% arm of a split test whose
// 30% arm is the natural read that is live today. Option A, operator 2026-08-25: the natural
// entries are not touched, so if the experiment is draft, paused or broken, 100% of visitors
// get exactly what they get now. An unproven method must never become the default by accident.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'

const DRAFTS = 'fb-tarot/docs/drafts/shadow/'
const OUT = 'client/src/content/tarotReadsShadow.ts'
const DECK = 'return-mhf'
const CARDS = ['a', 'b', 'c'] as const

type Draft = { hook: string; headline: string; decks: Record<string, Record<string, string[]>> }

const drafts: Draft[] = readdirSync(DRAFTS)
  .filter((f) => f.endsWith('.json'))
  .sort()
  .map((f) => JSON.parse(readFileSync(DRAFTS + f, 'utf8')))

const errors: string[] = []
for (const d of drafts) {
  const deck = d.decks[DECK]
  if (!deck) { errors.push(`${d.hook}: no ${DECK} deck`); continue }
  for (const c of CARDS) {
    const b = deck[c]
    if (!b) { errors.push(`${d.hook}/${c}: missing card`); continue }
    if (b.length !== 6) errors.push(`${d.hook}/${c}: ${b.length} beats, expected 6`)
    b.forEach((x, i) => { if (!x?.trim()) errors.push(`${d.hook}/${c} beat ${i + 1}: empty`) })
    if (b.some((x) => x.includes('\n'))) errors.push(`${d.hook}/${c}: a beat already contains a newline`)
  }
}
if (errors.length) {
  console.error('✗ the approved drafts did not validate — nothing was written:')
  for (const e of errors) console.error(`   ${e}`)
  process.exit(1)
}

// The fold. Six beats in, four slots out. Nothing is rewritten.
const fold = (b: string[]): string[] => [`${b[0]}\n${b[1]}`, b[2], `${b[3]}\n${b[4]}`, b[5]]

const esc = (s: string) => s.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n')
const body = drafts.map((d) => {
  const cards = CARDS.map((c) => {
    const slots = fold(d.decks[DECK][c]).map((s) => `        "${esc(s)}",`).join('\n')
    return `      ${c}: [\n${slots}\n      ],`
  }).join('\n')
  return `    // ${d.headline}\n    '${d.hook}': {\n${cards}\n    },`
}).join('\n')

writeFileSync(OUT, `// GENERATED by scripts/shadow-drafts-to-registry.mts — do not edit by hand.
//
// The Inherited Shadow reads: the 70% arm of the shadow-vs-natural split test. The 30% arm is
// the natural read in DECKS, which this file does not touch. Method spec:
// fb-tarot/docs/inherited-shadow-cut.md. Approved copy: fb-tarot/docs/drafts/shadow/*.json.
//
// To change a read, edit the DRAFT and re-run the generator. Editing here loses the change the
// next time anyone regenerates, and breaks the guarantee that what serves is what was approved.
//
// Folded [claim \\n proof] [her] [but \\n so] [loop] — six beats, four slots, six bubbles.
import type { TarotDeck, TarotHook, TarotOption } from './tarotReads'

export const SHADOW_READS: Partial<Record<TarotDeck, Partial<Record<TarotHook, Record<TarotOption, string[]>>>>> = {
  '${DECK}': {
${body}
  },
}

/** Does this hook have an Inherited Shadow read wired for this deck? */
export function hasShadowRead(deck: TarotDeck, hook: TarotHook): boolean {
  return Boolean(SHADOW_READS[deck]?.[hook])
}
`)

// ── Verify by unfolding: what went in must be what comes out ────────────────────────────────
const out = readFileSync(OUT, 'utf8')
let checked = 0
let bad = 0
for (const d of drafts) {
  for (const c of CARDS) {
    const src = d.decks[DECK][c]
    const m = out.match(new RegExp(`'${d.hook}': \\{[\\s\\S]*?${c}: \\[([\\s\\S]*?)\\],\\n`))
    const slots = [...(m?.[1] ?? '').matchAll(/^\s*"((?:[^"\\]|\\.)*)",$/gm)]
      .map((x) => x[1].replace(/\\n/g, '\n').replace(/\\"/g, '"').replace(/\\\\/g, '\\'))
    const beats = slots.flatMap((s) => s.split('\n'))
    for (let i = 0; i < 6; i++) {
      checked++
      if (beats[i] !== src[i]) { bad++; console.error(`   ✗ ${d.hook}/${c} beat ${i + 1} changed`) }
    }
  }
}
console.log(bad
  ? `✗ ${bad} of ${checked} bubbles differ — DO NOT SHIP`
  : `✓ ${drafts.length} landers · ${drafts.length * 3} reads · ${checked} bubbles, all verbatim`)
process.exitCode = bad ? 1 : 0
