// GENERATED by scripts/shadow-drafts-to-registry.mts — do not edit by hand.
//
// The Inherited Shadow reads: the 70% arm of the shadow-vs-natural split test. The 30% arm is
// the natural read in DECKS, which this file does not touch. Method spec:
// fb-tarot/docs/inherited-shadow-cut.md. Approved copy: fb-tarot/docs/drafts/shadow/*.json.
//
// To change a read, edit the DRAFT and re-run the generator. Editing here loses the change the
// next time anyone regenerates, and breaks the guarantee that what serves is what was approved.
//
// Folded [claim \n proof] [her] [but \n so] [loop] — six beats, four slots, six bubbles.
import type { TarotDeck, TarotHook, TarotOption } from './tarotReads'

export const SHADOW_READS: Partial<Record<TarotDeck, Partial<Record<TarotHook, Record<TarotOption, string[]>>>>> = {
  'return-mhf': {
    // Is there a soulmate for me after the marriage ended?
    'cards-after-marriage': {
      a: [
        "You turned the Magician. The three lay face down, and you took the one with nothing put away.\nLook at his table. A cup, a coin, a blade and a wand, all of them out.",
        "You asked if there's a soulmate after the marriage. This card makes me look at a table with all of it still out.",
        "But nobody has come. And you're asking whether that part of your life is done.\nSomething arrives just as this would get going. I don't think it began with you.",
        "Let me look closer at what it is…",
      ],
      b: [
        "You turned the Hanged Man. You couldn't see a face, and you found the one held by a single rope.\nLook at the rope. It's tied at one ankle, and the rest of him hangs loose.",
        "You asked if there's a soulmate after the marriage. What holds my eye is how little is doing the holding.",
        "Still, nobody has come. And you're the one carrying the question.\nWhatever has hold of this isn't moving. I don't think this began with you.",
        "Let me look closer at what this is…",
      ],
      c: [
        "You turned the Fool. Nothing showed through the backs, and you took the one already walking.\nLook at his feet. One is off the ground, and the other is about to follow.",
        "You asked if there's a soulmate after the marriage. This card brings me to a walk that's already begun.",
        "The part that doesn't fit is that nobody has come. And you're still asking.\nSomething is standing right where this would start. I don't think it started with you.",
        "Let me look closer at what's standing there…",
      ],
    },
    // Am I still allowed to want a soulmate?
    'cards-allowed-to-want': {
      a: [
        "You turned the Magician. You reached without seeing, and your hand landed on the busiest card here.\nLook at his hands. One is raised, the other points down, and both are working.",
        "You asked if you're still allowed to want a soulmate. What catches me is that neither hand is empty.",
        "Still, nobody has come. And you've started asking whether you're allowed to want it.\nWhatever is in the way of this holds steady. I don't think any of it began with you.",
        "Let me look closer at what's got hold of it…",
      ],
      b: [
        "You turned the Hanged Man. Nothing told the three apart, and you took the calmest man in the deck.\nHe hangs upside down by one ankle. Look at his face, though — it's calm.",
        "You asked if you're still allowed to want a soulmate. It's the pause itself I keep looking at.",
        "And yet nobody has come. And the question has turned into whether you may even ask it.\nSomething is sitting between you and this, close in. I don't think it began with you.",
        "Let me look closer at what's sitting there…",
      ],
      c: [
        "You turned the Fool. Face down, all three, and you took the one in full sun.\nLook at the sky behind him. It's gold, and there isn't a cloud in it.",
        "You asked if you're still allowed to want a soulmate. The sky is gold and his foot is already moving — that's what I'm looking at.",
        "But nobody has come. And you're the one asking whether it's alright to hope.\nSomething turns up as soon as this gets going. I don't think this began with you.",
        "Let me look closer at what that is…",
      ],
    },
    // Why did I give my best years to someone who wasn't my soulmate?
    'cards-best-years': {
      a: [
        "You turned the Magician. You couldn't see them, and your hand went to the worker of the three.\nLook at his hands. Both are busy, and neither one is resting.",
        "You asked why your best years went to someone who wasn't your soulmate. The thing I keep looking at is how much work is here.",
        "What troubles me is that they went to someone who wasn't the one. And you're the one left with the question.\nSomething sits in the way of this, close in rather than far off. I don't think it started with you.",
        "Let me look closer at what's sitting there…",
      ],
      b: [
        "You turned the Hanged Man. Nothing showed which was which, and you took the one held by one rope.\nLook at the rope. One ankle holds him, and nothing else does.",
        "You asked why your best years went to someone who wasn't your soulmate. The rope runs up into the beam, and that's what I'm reading.",
        "And yet they went to someone who wasn't the one. You're the one asking what those years were for.\nSomething arrives at the point where things would settle. I don't think any of it began with you.",
        "Let me look closer at what that is…",
      ],
      c: [
        "You turned the Fool. The backs gave nothing away, and you chose the one travelling light.\nLook at the bundle on his stick. That's all he's taking with him.",
        "You asked why your best years went to someone who wasn't your soulmate. A start made with very little — that's what this one shows me.",
        "They went to someone who wasn't the one, though. And you're the one asking why.\nWhatever holds this holds it steady, and it hasn't shifted. I don't think it began with you.",
        "Let me look closer at what's holding this…",
      ],
    },
    // Why do I keep getting blocked before my soulmate arrives?
    'cards-blocked-before': {
      a: [
        "You turned the Magician. You had nothing to go on, and you took the one who came ready.\nLook at his table. Four things laid out, and every one within reach.",
        "You asked why you keep getting blocked before your soulmate arrives. What catches me is that nothing on that table is held back.",
        "And yet nobody has come. And it has gone this way before.\nSomething is sitting in the gap itself. I don't think this began with you.",
        "Let me look closer at what's holding it…",
      ],
      b: [
        "You turned the Hanged Man. Nothing marked them apart, and you took the one held by a single thing.\nLook at the rope. One ankle, and the rest of him hangs free.",
        "You asked why you keep getting blocked before your soulmate arrives. This card shows how little it takes to hold all of it.",
        "Still, nobody has come. And it stops just before the part you're waiting for.\nThe hold is even — it never tightens and it never slackens. I don't think it started with you.",
        "Let me look closer at what's got hold of it…",
      ],
      c: [
        "You turned the Fool. Face down, all three, and you chose the one already stepping.\nLook at his feet. One has left the ground, and the other is following.",
        "You asked why you keep getting blocked before your soulmate arrives. This card brings me to a step in the middle of being taken.",
        "But nobody has come. And the stop comes early, before it gets going.\nSomething turns up just before that would happen. I don't think any of it began with you.",
        "Let me look closer at what's behind this…",
      ],
    },
    // Why is my money still blocked this close to retiring?
    'cards-blocked-retiring': {
      a: [
        "You turned the Magician. You couldn't see it, and your hand went to the worker of the three.\nLook at his hands. Both are busy, and neither one is resting.",
        "You asked why your money is still blocked this close to retiring. What catches me is how busy both those hands are.",
        "And yet it hasn't landed, dear. And retiring keeps getting nearer.\nThe hold is steady, and it doesn't loosen. I don't think it started with you.",
        "Let me look closer at what's holding it…",
      ],
      b: [
        "You turned the Hanged Man. Nothing showed which was which, and you took the one held by a single rope.\nLook at the rope. One ankle, and the rest of him hangs loose.",
        "You asked why your money is still blocked this close to retiring. I keep looking at where that rope goes.",
        "Still, it hasn't come through. And retiring is closer than it was.\nSomething is sitting between you and the money. I don't think any of it began with you.",
        "Let me look closer at what's doing the holding…",
      ],
      c: [
        "You turned the Fool. Face down, all three, and yours was the one in full sun.\nLook at the sky behind him. It's gold, and there's not a cloud in it.",
        "You asked why your money is still blocked this close to retiring. Broad daylight, and a foot already up.",
        "But it still hasn't landed. And you're the one asking why, this close in.\nSomething turns up right when it should land. I don't think it began with you.",
        "Let me look closer at what's there…",
      ],
    },
    // Is something blocking me from meeting my soulmate?
    'cards-blocking-soulmate': {
      a: [
        "You turned the Magician. You couldn't see a thing, and your hand found the busiest card here.\nLook at his hands. One points up, one points down, and both are working.",
        "You asked if something is blocking you from meeting your soulmate. What catches me is that neither of those hands is idle.",
        "And yet nobody has come. And you came in already suspecting something.\nSomething turns up at the point where this would start. I don't think it began with you.",
        "Let me look closer at what's doing that…",
      ],
      b: [
        "You turned the Hanged Man. The backs told you nothing, and you took the one held at one ankle.\nLook at the rope. It's a single line, and it does all the holding.",
        "You asked if something is blocking you from meeting your soulmate. One thin line does all the work here, and I can't get past it.",
        "Still, nobody has come. And that's the question you brought me.\nThe hold is light, and it doesn't slip. I don't think this began with you.",
        "Let me look closer at what's holding it…",
      ],
      c: [
        "You turned the Fool. Nothing showed through the backs, and you took the one travelling light.\nLook at the bundle on his stick. All he has is in it.",
        "You asked if something is blocking you from meeting your soulmate. A start with almost nothing carried — that's what I keep looking at.",
        "But nobody has come. And you're the one who came asking what's in the way.\nWhatever this is, it sits right where things begin. I don't think it started with you.",
        "Let me look closer at what's sitting right there…",
      ],
    },
    // What keeps me choosing everyone but my soulmate?
    'cards-choosing-wrong': {
      a: [
        "You turned the Magician. You had no way of knowing, and you took the one with it all laid out.\nLook at his table. A cup, a coin, a blade and a wand, out in the open.",
        "You asked what keeps you choosing everyone but your soulmate. It's the open table that stops me — nothing on it is hidden.",
        "And yet it keeps being everyone but the one. You've started to think it comes down to how you pick.\nSomething turns up each time this gets close to settling. I don't think this began with you.",
        "Let me look closer at what has hold of this…",
      ],
      b: [
        "You turned the Hanged Man. The backs told you nothing, and you found the calmest face in the deck.\nHe hangs by one ankle, upside down. Look at his face, though — it's calm.",
        "You asked what keeps you choosing everyone but your soulmate. What I'm reading is the hold itself, and how little of it there is.",
        "Still, it's everyone but the one. And the question keeps landing back on your judgement.\nThe hold on this is even, and nothing about it slips. I don't think it started with you.",
        "Let me look closer at what's behind this…",
      ],
      c: [
        "You turned the Fool. Nothing marked the backs, and you took the one already on the move.\nLook at his feet. One is off the ground, and the other is coming after it.",
        "You asked what keeps you choosing everyone but your soulmate. What I'm looking at is the moment before that step lands.",
        "But it's everyone but the one. And you're still the one asking why.\nSomething sits where that step comes down, at the front of this. I don't think any of it began with you.",
        "Let me look closer at what's sitting there…",
      ],
    },
    // Is my energy keeping my soulmate away?
    'cards-energy-away': {
      a: [
        "You turned the Magician. You couldn't see them, and your hand went to the one who came ready.\nLook at his table. A cup, a coin, a blade and a wand — all out.",
        "You asked if your energy is keeping your soulmate away. What catches me is that all four things are still out.",
        "Still, nobody has come. And you've started to think you're the reason.\nWhatever is in the way of this doesn't waver. I don't think any of it began with you.",
        "Let me look closer at what's doing that…",
      ],
      b: [
        "You turned the Hanged Man. Nothing told them apart, and you found the calmest man here.\nHe's upside down, held at the ankle. Look at his face, though — it's calm.",
        "You asked if your energy is keeping your soulmate away. What holds my eye is where that rope goes.",
        "And yet nobody has come. And the reason you're offering me is yourself.\nSomething stands between you and this, and not off in the distance. I don't think it began with you.",
        "Let me look closer at what that is…",
      ],
      c: [
        "You turned the Fool. Face down, all three, and yours was the one in full sun.\nLook at the sky behind him. Gold, and not a cloud in it.",
        "You asked if your energy is keeping your soulmate away. Open daylight, and a step already taken — that's what this one shows me.",
        "But nobody has come. And you're the one turning that question on yourself.\nSomething arrives right when this gets close. I don't think this began with you.",
        "Let me look closer at what's behind it…",
      ],
    },
    // How long has my energy been working against my money?
    'cards-energy-how-long': {
      a: [
        "You turned the Magician. Nothing marked them apart, and you took the one who came ready.\nLook at his table. A cup, a coin, a blade and a wand, laid out in front of him.",
        "You asked how long your energy has been working against your money. What catches me is that all four are lying out together.",
        "And yet it hasn't landed. And you've put that down to something in you.\nSomething stands between you and it, and it isn't far off. I don't think this began with you.",
        "Let me look closer at what's behind this…",
      ],
      b: [
        "You turned the Hanged Man. The backs told you nothing, and you took the one held at one ankle.\nLook at the rope. It's one line, at one ankle.",
        "You asked how long your energy has been working against your money. The rope, and what it runs into — that's what I stay on.",
        "Still, it hasn't come through. And how long is what you're asking me for.\nThe hold is even, and nothing about it varies. I don't think it started with you.",
        "Let me look closer at what's got hold of it…",
      ],
      c: [
        "You turned the Fool. Face down, all three, and you chose the one already stepping.\nLook at his feet. One has lifted, the other is still down.",
        "You asked how long your energy has been working against your money. This card brings me to a step already begun.",
        "But it still hasn't come. And you're the one asking how long it's been like this.\nSomething turns up right when the money would land. I don't think any of it began with you.",
        "Let me look closer at what that is…",
      ],
    },
    // What does my energy say about my soulmate?
    'cards-energy-soulmate': {
      a: [
        "You turned the Magician. Nothing showed through, and you took the one with nothing put away.\nLook at his table. It's out in the open, and all of it is in reach.",
        "You asked what your energy says about your soulmate. The thing I keep looking at is how much of this card is ready to hand.",
        "And yet nobody has come. And it's your own side of it you're asking about.\nSomething stands in the space between, close in. I don't think it started with you.",
        "Let me look closer at what it is…",
      ],
      b: [
        "You turned the Hanged Man. The backs gave nothing away, and yours was the card still growing.\nLook at the wood he hangs from. Green leaves, on living wood.",
        "You asked what your energy says about your soulmate. This card makes me look at something alive with a rope on it.",
        "Still, nobody has come. And the reading you want is of your own side.\nSomething comes in just as things would move. I don't think any of it began with you.",
        "Let me look closer at what's holding this…",
      ],
      c: [
        "You turned the Fool. You couldn't see the faces, and you chose the one already on his way.\nLook at his feet. One is lifted, the other still down.",
        "You asked what your energy says about your soulmate. The movement here has already started.",
        "But nobody has come. And you're the one asking what your part of it says.\nThe hold here is light, and it doesn't loosen. I don't think it began with you.",
        "Let me look closer at what's holding this…",
      ],
    },
    // Why hasn't my soulmate found me yet?
    'cards-found-me-yet': {
      a: [
        "You turned the Magician. Three backs, no way to tell, and you took the worker of the three.\nLook at his hands. Both are busy, and neither is resting.",
        "You asked why your soulmate hasn't found you yet. What catches me is that both hands have something to do.",
        "The part that doesn't fit is that nobody has found you. And you're the one who has been waiting.\nWhatever holds this hasn't shifted. I don't think it began with you.",
        "Let me look closer at what's holding it…",
      ],
      b: [
        "You turned the Hanged Man. Nothing showed which was which, and yours was the only card still growing.\nLook at the wood he hangs from. It's alive, with green leaves on it.",
        "You asked why your soulmate hasn't found you yet. What holds my eye is that the wood is still living.",
        "Still, nobody has found you. And the question has come back to you.\nSomething is standing between you and this, close in. I don't think this began with you.",
        "Let me look closer at what's behind this…",
      ],
      c: [
        "You turned the Fool. Face down, all three, and you took the one already on his way.\nLook at his feet. One is lifted, and the other is following it.",
        "You asked why your soulmate hasn't found you yet. The journey in this one is already under way.",
        "But nobody has found you. And you're still the one waiting.\nSomething is there at the start of it, turning up just as things move. I don't think it started with you.",
        "Let me look closer at what's got hold of it…",
      ],
    },
    // Do I need to heal before my soulmate arrives?
    'cards-heal-first': {
      a: [
        "You turned the Magician. You couldn't see the cards, and your hand went to the one who came ready.\nLook at his table. A cup, a coin, a blade, a wand — all of it already out.",
        "You asked whether you need to heal first. What catches me is that nothing on his table is missing.",
        "And yet nobody has come. You've started to wonder whether the missing part is you.\nSomething stands between you and this, close in. I don't think it began with you.",
        "Let me look closer at what's standing there…",
      ],
      b: [
        "You turned the Hanged Man. You couldn't see him, and your hand found the calmest man in the deck.\nHe's hanging upside down by one ankle. Look at his face, though — it's calm.",
        "You asked whether you need to heal first, dear. This card makes me look at the waiting in your question.",
        "Still, nobody has come. And somehow the question has turned back on you.\nWhatever has hold of this holds it quietly. I don't think this began with you.",
        "Let me look closer at what this is…",
      ],
      c: [
        "You turned the Fool. The cards were face down, but you still chose the one travelling light.\nLook at the small bundle on his stick. That's all he's taking with him.",
        "You asked whether you need to heal first. This card brings me to the very start of something.",
        "But nobody has come. And you're still wondering whether you're ready.\nSomething turns up right where this would start. I don't think it started with you.",
        "Let me look closer at what's behind this…",
      ],
    },
    // How much longer will something keep blocking my money?
    'cards-how-much-longer': {
      a: [
        "You turned the Magician. You had nothing to go on, and your hand found the worker of the three.\nLook at his hands. Both of them are busy, and neither is idle.",
        "You asked how much longer something will keep blocking your money. I keep going back to those two hands, both of them busy.",
        "Still, it hasn't landed. And what you want from me is a number.\nSomething turns up at the point where it would come through. I don't think it began with you.",
        "Let me look closer at what's doing the holding…",
      ],
      b: [
        "You turned the Hanged Man. Nothing showed through, and yours was the one held by a single rope.\nLook at the rope. One ankle, and nothing else on him.",
        "You asked how much longer something will keep blocking your money. One rope keeps this whole picture still.",
        "And yet it hasn't landed. And you're asking me how long that lasts.\nThe hold is constant, and it doesn't ease at any point. I don't think this began with you.",
        "Let me look closer at what's holding it…",
      ],
      c: [
        "You turned the Fool. Face down, all three, and you took the one travelling light.\nLook at the bundle on his stick. That's all he's carrying.",
        "You asked how much longer something will keep blocking your money. A start, and how little it needs — that's what I'm looking at.",
        "But it still hasn't landed. And you're the one asking how much longer.\nSomething sits right where the money would land. I don't think it started with you.",
        "Let me look closer at what's got hold of it…",
      ],
    },
    // How long does a soulmate keep you waiting?
    'cards-keeps-waiting': {
      a: [
        "You turned the Magician. You reached blind, and your hand found the one who came ready.\nLook at his table. Four things laid out, and every one in reach.",
        "You asked how long a soulmate keeps you waiting. What catches me is that all of it is already to hand.",
        "And yet nobody has come. And the waiting is what you're asking me to measure.\nSomething stands between you and this, close in. I don't think any of it began with you.",
        "Let me look closer at what's standing there…",
      ],
      b: [
        "You turned the Hanged Man. Face down, all three, and yours was the one still growing.\nLook at the wood he hangs from. Green leaves are on it, and it's alive.",
        "You asked how long a soulmate keeps you waiting. It's a pause with life still in it, and that's what stops me.",
        "Nobody has come, though. And how long is the whole of your question.\nThe hold is steady, and it hasn't slackened. I don't think it began with you.",
        "Let me look closer at what's got hold of it…",
      ],
      c: [
        "You turned the Fool. Nothing told them apart, and you took the only one in full sun.\nLook at the sky behind him. Gold, and not one cloud in it.",
        "You asked how long a soulmate keeps you waiting. A bright day, and the walking already begun.",
        "But nobody has come. And you're the one asking how long.\nSomething comes in at the moment this would move. I don't think this began with you.",
        "Let me look closer at what this is…",
      ],
    },
    // How much longer do I have to wait for my soulmate?
    'cards-longer-to-wait': {
      a: [
        "You turned the Magician. You couldn't tell one back from another, and you took the one who came ready.\nLook at his table. The tools are out, and none of them is put away.",
        "You asked how much longer you have to wait. I keep going back to that table — all out, none of it in use.",
        "Still, nobody has come. And the waiting is what you want measured.\nSomething turns up right when this would start moving. I don't think it started with you.",
        "Let me look closer at what's behind this…",
      ],
      b: [
        "You turned the Hanged Man. You couldn't see them, and you took the one hung from a single rope.\nLook at the rope. One ankle, and the rest of him swings free.",
        "You asked how much longer you have to wait. One rope is doing all of it.",
        "And yet nobody has come. And what you want from me is a number.\nThe hold is even — it doesn't pull, and it doesn't slacken. I don't think any of it began with you.",
        "Let me look closer at what's holding this…",
      ],
      c: [
        "You turned the Fool. Nothing showed through the backs, and you chose the one already stepping out.\nLook at his feet. One foot is up, and the other is under him.",
        "You asked how much longer you have to wait. The step in this one is already being taken.",
        "But nobody has come. And you're the one asking how much longer.\nSomething stands right where that step lands. I don't think it began with you.",
        "Let me look closer at what's holding this…",
      ],
    },
    // Is my soulmate still coming, or have I already missed him?
    'cards-missed-chance': {
      a: [
        "You turned the Magician. You couldn't see the faces, and your hand found the one who came ready.\nLook at his table. Nothing on it has been cleared away.",
        "You asked if he's still coming, or if you've missed him. What catches me is that the table is still set.",
        "The part that doesn't fit is that nobody has come. And you've put the harder half of that question to me yourself.\nWhatever is in the way holds steady, and it doesn't come and go. I don't think this began with you.",
        "Let me look closer at what's holding it…",
      ],
      b: [
        "You turned the Hanged Man. Nothing told them apart, and you found the calmest face in the deck.\nOne rope, one ankle, and he's upside down. His face, though — that's calm.",
        "You asked if he's still coming, or if you've missed him. It's the single rope that holds my eye.",
        "Still, nobody has come. And you've asked me to rule on it.\nSomething sits between you and the answer, close rather than far back. I don't think it started with you.",
        "Let me look closer at what this is…",
      ],
      c: [
        "You turned the Fool. Face down, all three, and you took the one standing in full sun.\nLook at the sky. It's gold, and there's not one cloud across it.",
        "You asked if he's still coming, or if you've missed him. This card brings me to broad daylight, and a foot already moving.",
        "But nobody has come. And you're the one carrying both halves of that question.\nSomething turns up at the point where this would come good. I don't think any of it began with you.",
        "Let me look closer at what has hold of this…",
      ],
    },
    // What does my energy say about why money won't stay?
    'cards-money-wont-stay': {
      a: [
        "You turned the Magician. Nothing told them apart, and you took the one who came ready.\nLook at his table. Four things on it, and all of them still in place.",
        "You asked what your energy says about money not staying. What catches me is that all four things sit on that table.",
        "Still, it doesn't stay, dear. It comes in and then it's gone again.\nWhatever is here holds steady, and nothing about it changes. I don't think any of it began with you.",
        "Let me look closer at what's got hold of it…",
      ],
      b: [
        "You turned the Hanged Man. Face down, all three, and yours was held by one rope.\nLook at the rope. One ankle, and the rest hangs free.",
        "You asked what your energy says about money not staying. What holds my eye is the single line of it.",
        "And yet it doesn't stay. And you've put that down to something in you.\nSomething sits at the point where it would settle. I don't think it began with you.",
        "Let me look closer at what's behind it…",
      ],
      c: [
        "You turned the Fool. You couldn't see them, and you chose the one travelling light.\nLook at the bundle on his stick. Small, and tied shut.",
        "You asked what your energy says about money not staying. How little is being carried — that's the part I keep looking at.",
        "But it doesn't stay. And you're the one asking why it goes.\nSomething turns up just as the money would stay. I don't think this began with you.",
        "Let me look closer at what's behind this…",
      ],
    },
    // Is my energy blocking my money?
    'cards-my-energy': {
      a: [
        "You turned the Magician. Nothing showed through, and your hand found the busiest of the three.\nLook at his hands. One raised, one down, and both of them working.",
        "You asked if your energy is blocking your money. What catches me is that both of those hands are moving.",
        "And yet it hasn't landed. And you've come in blaming yourself for that.\nSomething stands in the gap between you and it. I don't think it started with you.",
        "Let me look closer at what's doing that…",
      ],
      b: [
        "You turned the Hanged Man. The backs gave nothing away, and you found the calmest man in the deck.\nHe hangs by one ankle, upside down. Look at his face, though — it's calm.",
        "You asked if your energy is blocking your money. So much of this picture is being held — that's what I keep coming back to.",
        "Still, it hasn't come through. And the reason you're offering me is you.\nSomething arrives at the point where money would come in. I don't think any of it began with you.",
        "Let me look closer at what that is…",
      ],
      c: [
        "You turned the Fool. Face down, all three, and yours was the one in full sun.\nLook at the sky behind him. Gold, with not one cloud across it.",
        "You asked if your energy is blocking your money. Open daylight, and a step already under way.",
        "But it hasn't landed. And you're still the one asking what's wrong with yours.\nThe hold here is light, and it stays where it is. I don't think it began with you.",
        "Let me look closer at what's holding this…",
      ],
    },
    // How long has something been blocking me from a nest egg?
    'cards-nest-egg': {
      a: [
        "You turned the Magician. You couldn't see them, and your hand went to the worker of the three.\nLook at his hands. Both busy, and neither one empty.",
        "You asked how long something has been blocking your nest egg. What catches me is how full both those hands are.",
        "And yet nothing has gathered. And you're asking me how long it's been that way.\nSomething turns up at the point where things would start to build. I don't think this began with you.",
        "Let me look closer at what's holding it…",
      ],
      b: [
        "You turned the Hanged Man. Nothing marked the backs, and you took the one held at one ankle.\nLook at the rope. One ankle, and the rest of him hangs loose.",
        "You asked how long something has been blocking your nest egg. One rope holds all of it.",
        "Still, nothing has gathered. And how long is what you want from me.\nSomething has a quiet hold on this, and it doesn't shift. I don't think it started with you.",
        "Let me look closer at what that is…",
      ],
      c: [
        "You turned the Fool. Face down, all three, and you chose the one travelling light.\nLook at the bundle on his stick. That's all he owns.",
        "You asked how long something has been blocking your nest egg. A small bundle, and a step already taken — that's what stops me here.",
        "But nothing has gathered. And you're the one asking how long that's gone on.\nSomething sits right where it would gather. I don't think any of it began with you.",
        "Let me look closer at what's sitting there…",
      ],
    },
    // Will I find a new soulmate after loss?
    'cards-new-soulmate': {
      a: [
        "You turned the Magician. Three backs, and no way to know — yours was the one who came ready.\nLook at his table. A cup, a coin, a blade and a wand, all of them out.",
        "You asked whether you'll find a new soulmate after your loss. What catches me is how much is laid out on that table.",
        "Still, nobody has come. And you're the one left holding the question.\nWhatever is in the way of this holds steady, and it hasn't shifted. I don't think this began with you.",
        "Let me look closer at what's holding it…",
      ],
      b: [
        "You turned the Hanged Man. Nothing showed which was which, and yours was the card still growing.\nLook at the wood he hangs from. It's alive, with green leaves on it.",
        "You asked whether you'll find a new soulmate after your loss. What holds my eye is living wood with a rope through it.",
        "And yet nobody has come. And you're the one asking whether there's another.\nSomething stands between you and this, close by. I don't think it started with you.",
        "Let me look closer at what's holding this…",
      ],
      c: [
        "You turned the Fool. Face down, all three, and you took the only one in full sun.\nLook at the sky behind him. Gold, and not one cloud in it.",
        "You asked whether you'll find a new soulmate after your loss. The light is still on that day, and that's what I keep looking at.",
        "But nobody has come. And you're the one carrying that question now.\nSomething turns up the moment this would go anywhere. I don't think any of it began with you.",
        "Let me look closer at what's behind it…",
      ],
    },
    // Why haven't I found my soulmate where I am?
    'cards-not-found-yet': {
      a: [
        "You turned the Magician. Three backs, nothing to go on, and yours was the one who came ready.\nLook at his table. It's full, and it stands on open grass.",
        "You asked why you haven't found your soulmate where you are. What catches me is that the table is full wherever it stands.",
        "The part that doesn't fit is that nobody has come. And you've started to think the problem is where you are.\nThe hold is constant, and it doesn't come and go. I don't think it began with you.",
        "Let me look closer at what this is…",
      ],
      b: [
        "You turned the Hanged Man. Nothing showed which was which, and you took the one held at one ankle.\nLook at the rope. One ankle, and the rest of him is loose.",
        "You asked why you haven't found your soulmate where you are. One rope holds the whole of it in place.",
        "Still, nobody has come. And the question has turned into whether you're in the wrong spot.\nSomething is standing in the way of it, close in. I don't think this began with you.",
        "Let me look closer at what's behind this…",
      ],
      c: [
        "You turned the Fool. Face down, all three, and you chose the one already walking.\nLook at his feet. One is off the ground, and the other isn't far behind.",
        "You asked why you haven't found your soulmate where you are. What I'm looking at is a step being taken.",
        "But nobody has come. And you're the one asking whether you're standing in the wrong place.\nSomething turns up right as that step comes down. I don't think it started with you.",
        "Let me look closer at what it is…",
      ],
    },
    // Is something still blocking my money, or have I run out of time?
    'cards-out-of-time': {
      a: [
        "You turned the Magician. Nothing told the backs apart, and you took the one who came ready.\nLook at his table. A cup, a coin, a blade and a wand, all four in the open.",
        "You asked if something is blocking your money, or if time has gone. What catches me is that all four are still out.",
        "And yet it hasn't landed. And you've offered me the harder half yourself.\nWhatever is here holds without moving, and it doesn't come and go. I don't think it began with you.",
        "Let me look closer at what's got hold of it…",
      ],
      b: [
        "You turned the Hanged Man. Face down, all three, and yours was held at one ankle.\nLook at the rope. One line, one ankle, and nothing else.",
        "You asked if something is blocking your money, or if time has gone. It's the rope and the beam I keep looking at.",
        "Still, it hasn't come through. And you're asking me to rule between the two.\nSomething is sitting in front of it, close in. I don't think this began with you.",
        "Let me look closer at what that is…",
      ],
      c: [
        "You turned the Fool. Nothing showed through the backs, and yours was the one in full sun.\nLook at the sky behind him. Gold, and no cloud anywhere in it.",
        "You asked if something is blocking your money, or if time has gone. A bright day, and a lifted foot.",
        "But it hasn't landed. And you're the one asking which of the two it is.\nSomething turns up right at the point it would come. I don't think it started with you.",
        "Let me look closer at what's there…",
      ],
    },
    // I've prayed about money for years. What's still blocking it?
    'cards-prayed-years': {
      a: [
        "You turned the Magician. You had nothing to go on, and your hand found the worker of the three.\nLook at his hands. Both are busy, and neither one is still.",
        "You asked what's still blocking money you've prayed about. What catches me is that both those hands are busy.",
        "And yet it hasn't landed. And you're still the one asking what's holding it.\nSomething stands between you and it, close by. I don't think any of it began with you.",
        "Let me look closer at what's holding it…",
      ],
      b: [
        "You turned the Hanged Man. Nothing showed which was which, and you took the one held by one rope.\nLook at the rope. It's tied at one ankle, and that's the whole of it.",
        "You asked what's still blocking money you've prayed about. What holds my eye is that single rope and where it runs.",
        "Still, it hasn't come through. And the question you brought me is what's holding it.\nIt doesn't take much to hold this in place. I don't think it began with you.",
        "Let me look closer at what's holding it…",
      ],
      c: [
        "You turned the Fool. Face down, all three, and you chose the one already stepping.\nLook at his feet. One is off the ground, the other still down.",
        "You asked what's still blocking money you've prayed about. This card brings me to a foot already off the ground.",
        "But it hasn't landed. And you're the one still waiting on it.\nSomething turns up at the point where it would land. I don't think this began with you.",
        "Let me look closer at what's doing the holding…",
      ],
    },
    // How long will my prayers for money keep going unanswered?
    'cards-prayers-unanswered': {
      a: [
        "You turned the Magician. Nothing marked them apart, and you took the one who came ready.\nLook at his table. Four things laid out, none of them put back.",
        "You asked how much longer your prayers will go unanswered. What catches me is that all four sit within reach.",
        "And yet it hasn't landed. And what you want from me is a number.\nSomething turns up just as it would come through. I don't think it started with you.",
        "Let me look closer at what's behind this…",
      ],
      b: [
        "You turned the Hanged Man. The backs told you nothing, and yours was held by a single rope.\nLook at the rope. One ankle, and the rest of him hangs loose.",
        "You asked how much longer your prayers will go unanswered. This card makes me look at one rope taking all the weight.",
        "Still, it hasn't come through. And the quiet has gone on.\nThe hold is steady — it doesn't tighten and it doesn't ease. I don't think any of it began with you.",
        "Let me look closer at what's holding this…",
      ],
      c: [
        "You turned the Fool. Face down, all three, and yours was the one in full sun.\nLook at the sky behind him. It's gold, without a cloud in it.",
        "You asked how much longer your prayers will go unanswered. This card brings me to a gold sky with no cloud in it.",
        "But it hasn't landed. And you're the one still asking how long.\nSomething sits right where it would arrive. I don't think it began with you.",
        "Let me look closer at what's standing there…",
      ],
    },
    // Is he ever going to be ready for real commitment?
    'cards-ready-commit': {
      a: [
        "You turned the Magician. Nothing showed through the backs, and you took the one with nothing put away.\nLook at his table. It's out in the open, on the grass.",
        "You asked if he'll ever be ready for real commitment. I can't read him — what catches me is what's laid out on that table.",
        "And yet nothing has been settled. And you're the one left waiting on an answer.\nSomething turns up at the point where it would settle. I don't think any of it began with you.",
        "Let me look closer at what's got hold of it…",
      ],
      b: [
        "You turned the Hanged Man. The backs told you nothing, and you took the one held by a single rope.\nLook at the rope. One ankle, and the rest of him hangs loose.",
        "You asked if he'll ever be ready for real commitment. The hold is what I'm reading — one line, and nothing else.",
        "Still, nothing has been settled. And the waiting has landed on you.\nThe hold here is firm, and nothing about it eases. I don't think it began with you.",
        "Let me look closer at what that is…",
      ],
      c: [
        "You turned the Fool. Face down, all three, and you chose the one already stepping out.\nLook at his feet. One has lifted, and the other is following.",
        "You asked if he'll ever be ready for real commitment. The step here is being taken as we look at it.",
        "But nothing has been settled. And you're the one asking when it will be.\nSomething sits right where that step comes down. I don't think this began with you.",
        "Let me look closer at what's sitting there…",
      ],
    },
    // Am I ready to love again after losing him?
    'cards-ready-to-love': {
      a: [
        "You turned the Magician. Nothing showed through the backs, and you took the one with nothing put away.\nLook at his table. All he owns is out on it.",
        "You asked if you're ready to love again. What catches me is that the whole table is laid out.",
        "And yet nobody has come. And the question you brought is about yourself.\nSomething stands between you and this, right up against it. I don't think it began with you.",
        "Let me look closer at what's sitting there…",
      ],
      b: [
        "You turned the Hanged Man. The backs told you nothing, and you found the calmest man in the deck.\nHe hangs upside down from one ankle. Look at his face, though — it's calm.",
        "You asked if you're ready to love again, dear. This card makes me look at the pause in that question.",
        "Still, nobody has come. And you've asked me to say where you stand.\nSomething turns up at the point where this would open. I don't think this began with you.",
        "Let me look closer at what that is…",
      ],
      c: [
        "You turned the Fool. Face down, all three, and you chose the one travelling light.\nLook at the bundle on his stick. It's small, and that's all of it.",
        "You asked if you're ready to love again. This card brings me to a bundle small enough to carry in one hand.",
        "But nobody has come. And you're still the one asking.\nWhatever holds this holds it evenly, with no jolt in it. I don't think it started with you.",
        "Let me look closer at what's got hold of it…",
      ],
    },
    // How long does it take to find a soulmate the second time?
    'cards-second-time': {
      a: [
        "You turned the Magician. You reached without knowing, and you took the one with nothing put away.\nLook at his table. Every tool is out, and the table stands on open grass.",
        "You asked how long it takes the second time. The thing I keep looking at is the table, still laid out.",
        "And yet nobody has come. And what you want from me is how long.\nSomething sits in front of this, between you and it. I don't think it began with you.",
        "Let me look closer at what that is…",
      ],
      b: [
        "You turned the Hanged Man. Nothing showed you which was which, and yours was the card still growing.\nLook at the wood he hangs from. There are green leaves on it.",
        "You asked how long it takes the second time. Living wood, with a rope on it.",
        "Still, nobody has come. And the number you want is the whole of your question.\nSomething shows up at the moment things would settle. I don't think this began with you.",
        "Let me look closer at what's holding this…",
      ],
      c: [
        "You turned the Fool. The backs gave nothing away, and you chose the one travelling light.\nLook at the bundle on his stick. That's the whole of what he carries.",
        "You asked how long it takes the second time. A start already made — that's what this card shows me.",
        "But nobody has come. And you're still the one asking for a number.\nWhatever holds this holds it evenly, with no give in it. I don't think it started with you.",
        "Let me look closer at what's holding it…",
      ],
    },
    // Why does my soulmate keep slipping past me?
    'cards-slipping-past': {
      a: [
        "You turned the Magician. You couldn't see them, and your hand went to the busiest of the three.\nLook at his hands. Both are working, and neither is at rest.",
        "You asked why your soulmate keeps slipping past. What catches me is how much is in motion on this card.",
        "And yet it keeps slipping past you. It has gone this way before.\nSomething turns up each time this gets close. I don't think any of it began with you.",
        "Let me look closer at what has hold of this…",
      ],
      b: [
        "You turned the Hanged Man. Face down, all three, and you picked the one held at one ankle.\nLook at the rope. It holds one ankle, and nothing else touches him.",
        "You asked why your soulmate keeps slipping past. It's the rope I'm reading, and where it runs.",
        "Still, it slips past. And it has gone this way before.\nThe hold here is light, and it never tightens. I don't think it began with you.",
        "Let me look closer at what's there…",
      ],
      c: [
        "You turned the Fool. Nothing marked the backs, and you took the one already walking.\nLook at his feet. One is off the ground, and the other is right behind it.",
        "You asked why your soulmate keeps slipping past. The step in this one is still being made.",
        "But it keeps slipping past. And you're the one asking why.\nSomething is there at the moment things would hold. I don't think this began with you.",
        "Let me look closer at what's behind it…",
      ],
    },
    // Is my soulmate closer than I think?
    'cards-soulmate-closer': {
      a: [
        "You turned the Magician. Nothing marked the backs, and you took the one with nothing put away.\nLook at his table. It's all out, and all of it within arm's reach.",
        "You asked if your soulmate is closer than you think. What catches me is that nothing on that table had to be fetched.",
        "And yet nobody has come. And you're the one asking how close it is.\nSomething stands in between, close in rather than far off. I don't think any of it began with you.",
        "Let me look closer at what's there…",
      ],
      b: [
        "You turned the Hanged Man. The backs gave nothing away, and you found the calmest man in the deck.\nHe hangs by one ankle. Look at his face, though — it's calm.",
        "You asked if your soulmate is closer than you think. What holds my eye is how little is moving in this picture.",
        "Still, nobody has come. And the whole question you brought is how close it is.\nThe hold is quiet, and it doesn't strain. I don't think it began with you.",
        "Let me look closer at what's doing that…",
      ],
      c: [
        "You turned the Fool. You couldn't see a face, and yours was the one in full sun.\nLook at the sky. It's gold, and there's not one cloud in it.",
        "You asked if your soulmate is closer than you think. A bright day, and the walking started.",
        "But nobody has come. And you're still the one asking how far off it is.\nSomething turns up at the point where it would show. I don't think this began with you.",
        "Let me look closer at what's behind this…",
      ],
    },
    // Is there still a soulmate out there for me?
    'cards-soulmate-out-there': {
      a: [
        "You turned the Magician. Nothing marked them apart, and your hand went to the worker of the three.\nLook at his hands. Both are busy, and neither one is idle.",
        "You asked if there's still a soulmate out there for you. What catches me is that all four lie out in the open.",
        "And yet nobody has come. And you're the one asking whether it's still real.\nSomething turns up at the point where it would start. I don't think any of it began with you.",
        "Let me look closer at what's there…",
      ],
      b: [
        "You turned the Hanged Man. You couldn't see them, and yours was the only card still growing.\nLook at the wood he hangs from. Green leaves are on it, and it's living wood.",
        "You asked if there's still a soulmate out there for you. There's a rope on something still alive.",
        "Still, nobody has come. And you've been asking whether there's anything left to wait for.\nThe hold on this is steady, and nothing in it moves. I don't think it began with you.",
        "Let me look closer at what that is…",
      ],
      c: [
        "You turned the Fool. Face down, all three, and you took the one already stepping.\nLook at his feet. One is lifted, and the other is following.",
        "You asked if there's still a soulmate out there for you. This card brings me to a step in the middle of happening.",
        "But nobody has come. And you're the one asking whether any of it is still real.\nSomething sits at the point where that step lands. I don't think this began with you.",
        "Let me look closer at what's got hold of it…",
      ],
    },
    // Why am I still working when the money should have come by now?
    'cards-still-working': {
      a: [
        "You turned the Magician. You couldn't see them, and your hand found the worker of the three.\nLook at his hands. Both are busy, and neither has stopped.",
        "You asked why you're still working when the money should have come. What catches me is that both of those hands are at work.",
        "The part that doesn't fit is that nothing has come through. And you're the one still at it.\nSomething has a firm hold on this. I don't think this began with you.",
        "Let me look closer at what's got hold of it…",
      ],
      b: [
        "You turned the Hanged Man. Nothing showed which was which, and you took the one held at one ankle.\nLook at the rope. One ankle holds him, and nothing else does.",
        "You asked why you're still working when the money should have come. What holds my eye is the one rope, and where it ends.",
        "Still, nothing has come through. And you're the one carrying on regardless.\nSomething sits between the work and the pay, right in that gap. I don't think it started with you.",
        "Let me look closer at what's holding this…",
      ],
      c: [
        "You turned the Fool. Face down, all three, and you chose the one already stepping out.\nLook at his feet. One is lifted, and the other hasn't caught up.",
        "You asked why you're still working when the money should have come. What I keep looking at is a step already made.",
        "But nothing has come through. And you're still the one asking why.\nSomething turns up just when the money should land. I don't think any of it began with you.",
        "Let me look closer at what's there…",
      ],
    },
    // Is it too late to meet my soulmate?
    'cards-too-late-love': {
      a: [
        "You turned the Magician. You couldn't see a face, and your hand found the one who came ready.\nLook at his table. All four things are out, and none has been put back.",
        "You asked whether the moment has gone for meeting your soulmate. It's the laid-out table that stops me here.",
        "Still, nobody has come. And you've started to wonder whether the time for it has gone.\nThe hold is steady, and it hasn't eased. I don't think it started with you.",
        "Let me look closer at what's holding it…",
      ],
      b: [
        "You turned the Hanged Man. Nothing showed through, and yours was the only card still growing.\nLook at the wood he hangs from. It has green leaves on it, and it's alive.",
        "You asked whether the moment has gone for meeting your soulmate. What holds my eye is the green on that wood.",
        "And yet nobody has come. And the question you brought me is about time running out.\nSomething is sitting between you and this. I don't think any of it began with you.",
        "Let me look closer at what's behind this…",
      ],
      c: [
        "You turned the Fool. Face down, all three, and yours was the one in full sun.\nLook at the sky behind him. It's gold, and there isn't a cloud anywhere in it.",
        "You asked whether the moment has gone for meeting your soulmate. This card brings me to the middle of a bright day.",
        "But nobody has come. And you're the one asking whether the day is done.\nSomething turns up right where this would start. I don't think it began with you.",
        "Let me look closer at what's holding it…",
      ],
    },
    // Is something blocking my money, or did I just leave it too late?
    'cards-too-late': {
      a: [
        "You turned the Magician. Nothing told the three apart, and you took the one who came ready.\nLook at his table. Four things on it, and the table stands in the open.",
        "You asked if something is blocking your money, or if the moment has gone. What catches me is that all four are within reach.",
        "And yet it hasn't landed. And you've offered me the harsher half yourself.\nSomething stands between you and it, close in and squarely in the way. I don't think it began with you.",
        "Let me look closer at what this is…",
      ],
      b: [
        "You turned the Hanged Man. Face down, all three, and yours was held by one rope.\nLook at the rope. It's tied at one ankle, and that's all.",
        "You asked if something is blocking your money, or if the moment has gone. One rope can hold all of that.",
        "Still, it hasn't come through. And you're asking me to choose between the two.\nWhatever it is comes in right as the money would. I don't think this began with you.",
        "Let me look closer at what that is…",
      ],
      c: [
        "You turned the Fool. Nothing showed through, and yours was the only card in full sun.\nLook at the sky behind him. Gold, and not a cloud in sight.",
        "You asked if something is blocking your money, or if the moment has gone. That day is bright, and his foot is up.",
        "But it hasn't landed. And you're the one asking whether it's gone past you.\nWhatever holds this holds it firmly, and nothing in it moves. I don't think it started with you.",
        "Let me look closer at what's holding this…",
      ],
    },
    // Is my soulmate waiting for me to heal?
    'cards-waiting-to-heal': {
      a: [
        "You turned the Magician. You had nothing to go on, and your hand found the worker of the three.\nLook at his hands. One is raised, the other points down, and both are busy.",
        "You asked if your soulmate is waiting for you to heal. What catches me is that both hands are in the middle of something.",
        "And yet nobody has come. And you've put the hold-up at your end.\nSomething turns up right where this would move. I don't think this began with you.",
        "Let me look closer at what's got hold of it…",
      ],
      b: [
        "You turned the Hanged Man. Face down, all three, and you found the calmest face in the deck.\nHe hangs upside down from one ankle. Look at his face, though — it's calm.",
        "You asked if your soulmate is waiting for you to heal. What I'm reading is the rope, and the beam it runs up into.",
        "Still, nobody has come. And you've made yourself the reason for the wait.\nWhatever has hold of this holds it quietly. I don't think it started with you.",
        "Let me look closer at what that is…",
      ],
      c: [
        "You turned the Fool. Nothing marked the backs, and you took the one travelling light.\nLook at the bundle on his stick. It's small, and it's all he has.",
        "You asked if your soulmate is waiting for you to heal. What I'm looking at is a bundle small enough to walk with.",
        "But nobody has come. And you're still asking whether the delay is at your end.\nSomething sits at the point where this would start. I don't think any of it began with you.",
        "Let me look closer at what it is…",
      ],
    },
    // Where is my soulmate right now?
    'cards-where-soulmate': {
      a: [
        "You turned the Magician. Nothing showed through, and your hand found the busiest of the three.\nLook at his hands. One is up, one is down, and neither is empty.",
        "You asked where your soulmate is right now. What catches me is how much of this card is already in use.",
        "Still, nobody has come. And what you want from me is a where.\nSomething turns up right when this would get anywhere. I don't think it started with you.",
        "Let me look closer at what's doing that…",
      ],
      b: [
        "You turned the Hanged Man. Face down, all three, and yours was held by one rope.\nLook at the rope. It's tied at one ankle, and nothing else holds him.",
        "You asked where your soulmate is right now. The rope goes up into the beam, and that's what holds my attention.",
        "And yet nobody has come. And you're asking me to point somewhere.\nThe hold is fixed, and it stays put. I don't think any of it began with you.",
        "Let me look closer at what's got hold of it…",
      ],
      c: [
        "You turned the Fool. Nothing told them apart, and you took the one travelling light.\nLook at the bundle on his stick. That's all he's carrying.",
        "You asked where your soulmate is right now. Travelling, and what gets carried with it — that's where this one puts me.",
        "But nobody has come. And you're the one asking for a location.\nSomething is sitting right in the middle of this. I don't think it began with you.",
        "Let me look closer at what's doing that…",
      ],
    },
    // Will he ever commit?
    'cards-will-commit': {
      a: [
        "You turned the Magician. You couldn't see them, and your hand went to the busiest of the three.\nLook at his hands. Both are busy, and neither is resting.",
        "You asked whether he'll ever commit. A card can't see inside him — what catches me is how much here is already out.",
        "And yet nothing has been settled. And you're the one holding the question.\nWhatever is in the way of this holds steady, and it doesn't ease off. I don't think it started with you.",
        "Let me look closer at what's holding it…",
      ],
      b: [
        "You turned the Hanged Man. Nothing marked the backs, and you found the calmest man in the deck.\nHe hangs upside down from one ankle. Look at his face, though — it's calm.",
        "You asked whether he'll ever commit. What holds my eye is the rope, and the beam above it.",
        "Still, nothing has been settled. And you're the one still wondering why.\nSomething is standing between you and the answer. I don't think any of it began with you.",
        "Let me look closer at what's there…",
      ],
      c: [
        "You turned the Fool. Face down, all three, and you took the one travelling light.\nLook at the bundle on his stick. That's the whole of what he owns.",
        "You asked whether he'll ever commit. This card brings me to a beginning carrying almost nothing.",
        "But nothing has been settled. And you're still the one asking.\nSomething turns up right where a start would be. I don't think it began with you.",
        "Let me look closer at what's holding this…",
      ],
    },
    // Why won't he commit to me?
    'cards-wont-commit': {
      a: [
        "You turned the Magician. Nothing told them apart, and you took the one who came ready.\nLook at his table. A cup, a coin, a blade and a wand — all of it out.",
        "You asked why he won't commit to you. I can't read his reasons — but nothing on that table is held back.",
        "And yet nothing has been settled. And you've started to think the reason is you.\nSomething stands in between, close in and not far off. I don't think this began with you.",
        "Let me look closer at what's standing there…",
      ],
      b: [
        "You turned the Hanged Man. Face down, all three, and yours was held by one rope.\nLook at the rope. One ankle, and nothing else on him.",
        "You asked why he won't commit to you. It's the hold itself I'm reading, not his reasons.",
        "Still, nothing has been settled. And the question has turned back on you.\nThe hold is quiet — it doesn't pull, and it doesn't move. I don't think it started with you.",
        "Let me look closer at what this is…",
      ],
      c: [
        "You turned the Fool. Nothing showed through the backs, and you chose the one already on the move.\nLook at his feet. One is up, and the other is coming after it.",
        "You asked why he won't commit to you. The step here is already in motion.",
        "But nothing has been settled. And you're the one asking why.\nSomething turns up right at the point it would settle. I don't think any of it began with you.",
        "Let me look closer at what's behind this…",
      ],
    },
  },
}

/** Does this hook have an Inherited Shadow read wired for this deck? */
export function hasShadowRead(deck: TarotDeck, hook: TarotHook): boolean {
  return Boolean(SHADOW_READS[deck]?.[hook])
}
